import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Map from 'react-map-gl'
import DeckGL from '@deck.gl/react';
import { NewYorkTreesLayer } from '../layers/scatterplot/new-york-trees'
import { CATransitStops } from '@/layers/heatmap/ca-stops';
const MAPBOX_TOKEN = 'pk.eyJ1IjoieXV5YWZ1amltb3RvIiwiYSI6ImNsZWdyZDA4NTA1ZGwzeG53Y2c2OGY0bjAifQ._mbKMYj_moCfX1GcJmxAJg'
const INITIAL_VIEW_STATE = {
  longitude: -122.4,
  latitude: 37.8,
  zoom: 5,
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <DeckGL
          initialViewState={INITIAL_VIEW_STATE}
          layers={CATransitStops.layer}
          controller={true}
        >
          <Map
            className=""
            initialViewState={INITIAL_VIEW_STATE}
            mapStyle="mapbox://styles/mapbox/light-v11"
            mapboxAccessToken={MAPBOX_TOKEN}
          />
        </DeckGL>
      </main>
    </>
  );
}
